### ISSUE TITLE
Tutorial is out of date

### ISSUE THREAD

**Issue by kenomaerz** [kuzmoyev/google-calendar-simple-api#104]
The querying process apparently changed a little since I last used the project, and using the former default query of  calendar[start_date:end_date] now doesn't return single events by default. This leads to the [quick example](https://google-calendar-simple-api.readthedocs.io/en/latest/getting_started.html) generating unexpected behavior, i.e. returning only one instance.  That might need some additional explanation. I would suggest to reference single_events and the ordering option there immediately.

Glad you are still working on this!

**Comment by kuzmoyev** [comment]
Oh. Thank you for noting that. I will go through it and fix it ASAP
