### ISSUE TITLE
When installing I get the following error...

### ISSUE THREAD

**Issue by dhindry** [kuzmoyev/google-calendar-simple-api#109]
Hello when installing from pip I get the following error

Collecting beautiful-date>=2.0.0 (from gcsa)
  Could not find a version that satisfies the requirement beautiful-date>=2.0.0 (from gcsa) (from versions: )
No matching distribution found for beautiful-date>=2.0.0 (from gcsa)

I have not been able to find out what that means, any suggestions?

**Comment by kuzmoyev** [comment]
There is a template for the issue. Please follow it to include more context and steps to reproduce it, specifically commands that you use. I can't reproduce it with `pip install gcsa`.

**Comment by kuzmoyev** [comment]
Closing the issue because of inactivity. Let me know if it needs more attention.
