### ISSUE TITLE
Issue with expired token

### ISSUE THREAD

**Issue by MarinBons** [kuzmoyev/google-calendar-simple-api#118]
Hello ! Thank you for your amazing project :)
I've got issues with tokens. I've ran the program to have a token in a pickle file, it worked : I could access to my events etc. And just a week after it stopped working.

I've the API this way : 

```
from gcsa.google_calendar import GoogleCalendar
import time

while True:
    try:
        calendar = GoogleCalendar(email_address)
        for event in calendar:
            print(event)
        print("Success")
    except Exception as e:
        print("Error")
        print(e)  
    time.sleep(a_day)
```

And had the error :

`('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})`

Do you know why ? I thought just initializing GoogleCalendar would refresh the token when needed.

Thanks :)

**Comment by kuzmoyev** [comment]
Hello. Thank you for the issue submission. Could you please follow the issue template (choose "bug report" when creating the issue)? Specifically, please include the whole traceback.

**Comment by kuzmoyev** [comment]
Closing the issue due to inactivity. Please, let me know if this needs more attention.
