### ISSUE TITLE
Query timezone of calendar for events?

### ISSUE THREAD

**Issue by Adawg4** [kuzmoyev/google-calendar-simple-api#127]
I know this may not be an actual bug rep but really wanted to ask if there was a way to query the calendars current timezone because we use a UTC server with this package and people want to schedule events in their calendars default tz?

You are a legend!

**Comment by kuzmoyev** [comment]
Hey, thanks for your question.

Unfortunately, there is no implementation of the calendar and calendarList processing (talking about #62).

As a workaround, you can use `GoogleCalendar.service` field:

```
gc = GoogleCalendar(...)
calendar_json = gc.service.calendars().get(calendarId='primary').execute()
tz = calendar_json['timeZone']
```

This will give you _The time zone of the calendar. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".)_

See more [here](https://developers.google.com/calendar/api/v3/reference/calendars) and [here](https://developers.google.com/calendar/api/v3/reference/calendars/get).

In future, you can use [GitHub Discussions](https://github.com/kuzmoyev/google-calendar-simple-api/discussions) or [Discord server](https://discord.gg/kVXG4Gra).

Will close the issue. If you have any more questions, please, feel free to reach out!
