### ISSUE TITLE
Service Accounts

### ISSUE THREAD

**Issue by angela-d** [kuzmoyev/google-calendar-simple-api#129]
Not sure if there's a simpler way to do this that I overlooked in the docs, but when I use a service account to pull events, I get blank events.  No error, just nothing.

- I have shared the calendar with the service account email, that was issued by Google on https://console.cloud.google.com/apis/credentials?project=my-project

- If I view logs at:
  - Edit (beside the service account)
  - Logs
    - > No entries found matching that current filter.

- View Metrics:
  - Metrics (beside Logs) tab
    - Activity is shown

Here's what I'm doing:
```python
import gcsa.event
from gcsa.google_calendar import GoogleCalendar
import gcsa.recurrence
from google.oauth2 import service_account

SCOPES = ['https://www.googleapis.com/auth/calendar']
SERVICE_ACCOUNT_FILE = '/home/user/.credentials/serviceacctkey.json'

credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=SCOPES)


calendar = GoogleCalendar('example_targetcalendar@group.calendar.google.com', credentials=credentials)

for event in calendar:
    print(event)
```

Is there a better way to do this, or did I miss a step?

**Comment by angela-d** [comment]
There is no event data returned and no error.

If I connect as my user (not a service account) the event data returns as expected.

**Comment by kuzmoyev** [comment]
Does [this](https://stackoverflow.com/a/60039606/4727702) help?
Unfortunately, this seems like a google API thing and not GCSAs.

But do let me know if this doesn't help or you have any questions. I'm happy to help.

**Comment by angela-d** [comment]
The service accounts seem to vary with how they're handled by Google, opposed to standard accounts; thanks for the link!  You led me in the right direction.

Here's what I ended up doing, in case anyone else runs into what I did. (This is using a Google Workspace service account and not a standard Google account)

[Reference](https://stackoverflow.com/questions/69574538/use-the-calendar-api-without-human-interaction)
1. Get OAuth client ID from: https://console.developers.google.com/iam-admin/serviceaccounts

2. Go to admin.google.com > Security > APIs > Manage Delegated Accounts
    - Add client ID from step 1
    - Under scopes: https://www.googleapis.com/auth/calendar
    - Authorize

The code snippet @kuzmoyev referenced, too:

```python
import gcsa.event
from gcsa.google_calendar import GoogleCalendar
from datetime import datetime, time, timedelta
import pytz

CALENDAR_ID='...@group.calendar.google.com'
SCOPES = ['https://www.googleapis.com/auth/calendar']
SERVICE_ACCOUNT_FILE = '/home/user/.credentials/serviceacctkey.json'

# used to calculate the start/end date of events i want to pull
tz = pytz.timezone('America/New York')
start_date = tz.localize(datetime.today())
tomorrow = tz.localize(datetime.today() + timedelta(days=1))
end_date = tz.localize(datetime.combine(tomorrow, datetime.max.time()))

# authorize
calendar_auth = GoogleCalendar(CALENDAR_ID, credentials_path=SERVICE_ACCOUNT_FILE)

# service acct insert (since we can't login to 'add' it)
calendar_list_entry = {
    'id': CALENDAR_ID
}
calendar_list = calendar_auth.service.calendarList().insert(body=calendar_list_entry).execute()
print(calendar_list['summary'])

# get today and tomorrow's events
calendar_events = calendar_auth.get_events(start_date, end_date, single_events=True, order_by='startTime')

for event in calendar_events:
    print(event)
```

**Comment by kuzmoyev** [comment]
Great!
Thank you for sharing a detailed solution
