### ISSUE TITLE
Combining mulitple calendars into one

### ISSUE THREAD

**Issue by vancheese** [kuzmoyev/google-calendar-simple-api#132]
Is there a way to combine two more  calendars into a single calendar without iterating through each calendar? 

My Use case

I've multiple calendars which I want to display upcoming events on a single timeline

**Comment by kuzmoyev** [comment]
There is no way to do it in google's API (AFAIC), hence is no way to do it in GCSA. You need to iterate over all calendars.

Note: you can [import](https://google-calendar-simple-api.readthedocs.io/en/latest/events.html#import-event) events from a different calendar to create a copy of the event.
Another note: if you get events from different calendars, you can merge them into one list and just sort. As `Event`s are sortable.

For feature, please use [GitHub discussions](https://github.com/kuzmoyev/google-calendar-simple-api/discussions) page or [Discord server](https://discord.gg/kVXG4Gra) for questions and not actual issues.

Will close the issue for now.

**Comment by vancheese** [comment]
Thanks for the speedy response and sorry for using the wrong channel

**Comment by kuzmoyev** [comment]
Sure, no problem :)
