### ISSUE TITLE
Support tasks and reminders

### ISSUE THREAD

**Issue by Eikosa** [kuzmoyev/google-calendar-simple-api#138]
![image](https://user-images.githubusercontent.com/20538090/183244051-e8381fbe-a7a1-4c90-9487-40c7729e9109.png)
![image](https://user-images.githubusercontent.com/20538090/183244054-b792e8a6-c897-4875-bd91-066bf34f0f95.png)

**Comment by kuzmoyev** [comment]
Hi @Eikosa, thank you for the submission.

Reminders are already supported, see [Reminders docs](https://google-calendar-simple-api.readthedocs.io/en/latest/reminders.html).

"Tasks" is a [separate API](https://developers.google.com/tasks), not a part of the "Calendar" API, so it can/should probably be a separate library.

In the future, please don't post non-Engish-UI screenshots and include some more detailed descriptions of the issue/feature request.

I will close the issue. If you think it needs more attention, feel free to contact me here, in [GitHub Discussions](https://github.com/kuzmoyev/google-calendar-simple-api/discussions), or on [Discord](https://discord.gg/mRAegbwYKS)
