### ISSUE TITLE
Type Error: Missing required parameter "eventId"

### ISSUE THREAD

**Issue by flashstacks06** [kuzmoyev/google-calendar-simple-api#150]
Hello I'm carlos, I had an issue with my code, I wanna add an event and then add an attendee but when I want to update my event, drop me the error Type Error: Missing required parameter "eventId" and I can't understand why?, could you help me with my issue please, I leave my code here 

python: 3.10.7
windows 11

```
from calendar import Calendar
from gcsa.event import Event
from gcsa.google_calendar import GoogleCalendar
from gcsa.recurrence import Recurrence, DAILY, SU, SA
from gcsa.attendee import Attendee

from beautiful_date import *


def classtogooglecal():


    calendar = GoogleCalendar('myemail@gmail.com',credentials_path='credentials.json')

    event = Event('Prueba',start=(25 / Oct / 2022)[21:58],minutes_before_email_reminder=20)

    attendee = Attendee('example@gmail.com')

    calendar.add_event(event)

    event.add_attendee(attendee)

    calendar.update_event(event)

classtogooglecal()
```

**Comment by kuzmoyev** [comment]
`calendar.add_event(event)` returns a created event with the set id. So replace this line with

```
event = calendar.add_event(event)
```

And everything should work.

But if adding the attendee is the only update you do to the event, you can just add attendee before `add_event`:

```
...
attendee = Attendee('example@gmail.com')
event = Event('Prueba', 
                         start=(25 / Oct / 2022)[21:58], 
                         minutes_before_email_reminder=20, 
                         attendees=attendee)
calendar.add_event(event)
```

Also, glad to see that you are using `beautiful-date` 😊

**Comment by flashstacks06** [comment]
Thank you so so much, it works, and the reason for using the instruction attendee instead of just adding in event instruction is that I wanna make a function where a can only enter emails and be able to delete them as well as add them, and a think I cloud do that with a for, I don't know, what do u think?

**Comment by flashstacks06** [comment]
and btw, I love beautiful-date, its so easy to use, and very useful

**Comment by kuzmoyev** [comment]
Happy that this resolved your issue.

Just a suggestion (as per [attendees docs](https://google-calendar-simple-api.readthedocs.io/en/latest/attendees.html)) you can simply pass a list of `Attendees` or list of emails to the event:

```
emails = ["firstemail@gmail.com","secondone@gmail.com"]
event = Event('Prueba',
                         start=(25 / Oct / 2022)[21:58],
                         minutes_before_email_reminder=20,
                         attendees=emails)
event = calendar.add_event(event)
```
GCSA will create `Attendee` objects for you.

I'll close the issue. If you have any other questions post them here or in the [Discussions](https://github.com/kuzmoyev/google-calendar-simple-api/discussions].
