### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by KhudadadKhawari** [kuzmoyev/google-calendar-simple-api#151]
ImportError: cannot import name 'Event' from partially initialized module 'gcsa.event' (most likely due to a circular import)

**Comment by kuzmoyev** [comment]
Please follow the [bug report template](https://github.com/kuzmoyev/google-calendar-simple-api/issues/new?assignees=&labels=&template=bug_report.md&title=). With no context/code/full traceback it's hard to help

**Comment by kuzmoyev** [comment]
Closing the issue due to inactivity. If you'd like to discuss this further please provide more details here, in Discussions, or in Discord.
