### ISSUE TITLE
Issue when changing event type

### ISSUE THREAD

**Issue by jnikolouzos** [kuzmoyev/google-calendar-simple-api#161]
## Bug description
When I tried to create a new event with event type "outOfOffice" or "focusTime", it creates a "default" one.

By debugging, I narrowed down the issue on the following call in events_service:
event_json = self.service.events().insert(...).execute()

Even though body has eventType: focusTime, event_json has eventType: default

https://developers.google.com/calendar/api/v3/reference/events
```
eventType | string | Specific type of the event. Read-only. Possible values are:"default" - A regular event or not further specified."outOfOffice" - An out-of-office event."focusTime" - A focus-time event.
```

## To Reproduce

1. Installed the latest version with `pip install gcsa`
2. execute the following code

Code used:

```python
from datetime import datetime, timedelta
from gcsa.event import Event
from gcsa.google_calendar import GoogleCalendar


if __name__ == '__main__':
    event = Event(summary="test",
                  start=datetime.strptime("02/05/2023 12:00", "%m/%d/%Y %H:%M"),
                  end=datetime.strptime("02/05/2023 13:00", "%m/%d/%Y %H:%M"),
                  eventType="focusTime"
                  )
    calendar = GoogleCalendar(my_email)
    print(calendar.add_event(event))

```

## Error or unexpected output

The eventType is "default"

## Expected behavior

The eventType remain "focusTime" or "outOfOffice"

## Tech:

- OS: Linux
- GCSA version: 2.0.1
- Python version: 3.9

**Comment by kuzmoyev** [comment]
Hi @jnikolouzos, thank you for the issue submission. Unfortunately, `eventType` is a read-only field in google's API. It is ignored on the `.insert()` (`add_event`) requests. There's nothing we can do from the GCSA side.

Here's the (5 years old) [feature request](https://issuetracker.google.com/issues/112063903?pli=1) for that on their issue tracker. I've +1-ed it, you can too. But I wouldn't keep my hopes high.

Let's keep your issue open for future reference.

**Comment by jnikolouzos** [comment]
Hi @kuzmoyev,

Thanks ultra fast reply.

Best regards,
Jim Nikolouzos

**Comment by kuzmoyev** [comment]
Just cleaning up. Will reopen if it's ever implemented in the official API.
Thanks for the submission anyway!
