### ISSUE TITLE
Clarify get_events() docs

### ISSUE THREAD

**Issue by mstuebner** [kuzmoyev/google-calendar-simple-api#167]
## Bug description

Using get_events() as mentioned in documentation (https://google-calendar-simple-api.readthedocs.io/en/latest/events.html#list-events), get_events() doesn't have any effect.

With the code below exactly the same events as without a call of get_events() are returned, also outside the defined start and end dates.

## To Reproduce

1. Installed the latest version with `pip install gcsa`
2. execute code below

Code used:

```python
import datetime

from gcsa.event import Event
from gcsa.google_calendar import GoogleCalendar
from gcsa.recurrence import Recurrence, DAILY, SU, SA

from beautiful_date import Jan, Apr


calendar = GoogleCalendar('xyz@gmail.com')

calendar.get_events(start_date=datetime.date(2023, 1, 1),
                    end_date=datetime.date(2023, 12, 31),
                    single_events=True,
                    order_by='startTime')

for event in calendar:
    print(event)
```

## Error or unexpected output

Events far outside the start and end are displayed.

## Tech:

- OS: MacOS
- GCSA version: 2.1.0
- Python version: 3.11.1

## Additional context

None

**Comment by kuzmoyev** [comment]
Hi, thank you for the issue submission.

`.get_events()` returns the iterable of events. Just iterate over it:

```python
events = calendar.get_events(start_date=datetime.date(2023, 1, 1),
                    end_date=datetime.date(2023, 12, 31),
                    single_events=True,
                    order_by='startTime')

for event in events:
    print(event)
```

I'll think about clarifying the documentation on this. I'll close the issue. If you have any questions, feel free to ask them here, in GitHub Discussions, or on discord.

**Comment by mstuebner** [comment]
Thats what I did too, but using your code results in an error:
```python
  File "/Users/mstuebner/PycharmProjects/google_calendar/.venv/lib/python3.11/site-packages/googleapiclient/discovery.py", line 1048, in method
    raise TypeError("Got an unexpected keyword argument {}".format(name))
TypeError: Got an unexpected keyword argument start_date
```

**Comment by kuzmoyev** [comment]
Right, didn't notice that issue. The correct arguments' names are `time_min` and `time_max`:

```
events = calendar.get_events(time_min=datetime.date(2023, 1, 1),
                    time_max=datetime.date(2023, 12, 31),
                    single_events=True,
                    order_by='startTime')

for event in events:
    print(event)
```

**Comment by mstuebner** [comment]
confirmed working, thanks.
