### ISSUE TITLE
ModuleNotFoundError on raspberrypi

### ISSUE THREAD

**Issue by Kocher04** [kuzmoyev/google-calendar-simple-api#172]
Hey,
I've got an ModuleNotFoundError while running my Python script. 
I am trying to run the script on an raspberrypi. So I have installed gcsa with 'pip install gcsa' but still the error shows up.
The error showed because of this import: 'from gcsa-google_calendar import GoogleCalendar'.
I have tested the script on my pc. It works perfectly fine there.

**Comment by kuzmoyev** [comment]
Hi, please follow the [bug report template](https://github.com/kuzmoyev/google-calendar-simple-api/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) to include all needed information, i.e. full traceback, actual code you use (`from gcsa-google_calendar import GoogleCalendar` has syntax error). Make sure that you run your script with the same Python where you install the gcsa, check [this question and answer](https://stackoverflow.com/questions/44528638/after-pip-successful-installed-modulenotfounderror).

**Comment by Kocher04** [comment]
## To Reproduce

Steps to reproduce the behavior:

1. Installed the latest version with `pip3 install gcsa`
2. run script via 'sudo python script.py'

Code used:

```python
from gcsa.google_calendar import GoogleCalendar
```

## Error or unexpected output
```
Traceback (most recent call last):
  File "/home/kocher/ValdesKalender/Kalender.py", line 7, in <module>
    from gcsa.google_calendar import GoogleCalendar
ModuleNotFoundError: No module named 'gcsa'
```

## Tech:
- raspberrypi 
- Python version: 3.9.2

## Additional context

I have tested the script local on my pc where it runs without any problems...
hope you have got all the information you need to help me with that. 
Thank you!

**Comment by kuzmoyev** [comment]
Try running without `sudo` (just `python script.py`)

**Comment by Kocher04** [comment]
Ah well, that was an easy one... haha thank you. 
One more: 
The authentication Page leads me to ```localhost:8080```. Of course this one doesn't exists since I run the script on the raspberrypi. How can I fix this?

**Comment by kuzmoyev** [comment]
You can use `authentication_flow_host` (and `authentication_flow_port` if needed). See [here](https://google-calendar-simple-api.readthedocs.io/en/latest/code/google_calendar.html#googlecalendar)

**Comment by Kocher04** [comment]
I already fixed it with just copying the token from my pc

**Comment by kuzmoyev** [comment]
Great! Glad it works now
