### ISSUE TITLE
Adding Multiple Attendees to an existing event

### ISSUE THREAD

**Issue by kolahimself** [kuzmoyev/google-calendar-simple-api#180]
I noticed that the `add_attendee()` method takes in one single email address, is there anyway in which i can invite multiple attendees by passing a list of their emails?

**Comment by kuzmoyev** [comment]
There's no such method. So

```python
event = ...
attendees = ['abc@gmail.com', 'bcd@gmail.com']

for a in attendees:
    event.add_attendee(a)
```

I'll think about adding a method to add multiple attendees at once.

Thanks for the submission!

**Comment by kolahimself** [comment]
just as i thought, thanks for the reply. welldone

**Comment by kuzmoyev** [comment]
Let's leave it open until I add this in the next version.
