### ISSUE TITLE
Constructor arguments with default `None` are missing `Optional` type annotations

### ISSUE THREAD

**Issue by roeehendel** [kuzmoyev/google-calendar-simple-api#197]
## Bug Description

Constructor arguments that are set by default to `None` are not annotated with `Optional[Type]` or `Type | None`. This is not consistent with PEP 484, which suggests that parameters that can be `None` should be explicitly marked as `Optional` to make the code more readable and to improve type checking.

## Example

In the following example, the `credentials` parameter is set to `None` by default but is not typed as `Optional`:

```python
class GoogleCalendar:
    ...
    def __init__(
            self,
            ...
            credentials: Credentials = None,
            ...
    ):
```

## Expected Behavior

The parameter should be typed with `Optional[Credentials]` to make it clear that `None` is an acceptable value. 

Corrected code:

```python
class GoogleCalendar:
    ...
    def __init__(
            self,
            ...
            credentials: Optional[Credentials] = None,
            ...
    ):
```

**Comment by kuzmoyev** [comment]
Thanks for the submission!

Excellent point! The initial motivation behind leaving out `Optional` was for readability purposes (as default `None` already suggests that the argument is optional) both in code and docs. But as type annotations become more common, we should follow the standard and be explicit.

Will update it in the next version.
