### ISSUE TITLE
Start point for GoogleCalendar iteration is off.

### ISSUE THREAD

**Issue by doctorwheauxdat** [kuzmoyev/google-calendar-simple-api#26]
If I use 
```python
for event in calendar:
    print(event)
```
and there is an event on the current day, but it happens fairly soon, that event will not be printed. Say for example, it is currently 2:00PM and I have an Event at 3:30PM.

**Comment by kuzmoyev** [comment]
Sounds like a timezone problem/bug. Will look into it.
Thank you for issue submission

**Comment by kuzmoyev** [comment]
Until the update, you should be able to use:

    for event in calendar.get_events(datetime.now()):
        print(event)

**Comment by kuzmoyev** [comment]
Now you can upgrade to `gcsa=0.3.1` with the fix.
