### ISSUE TITLE
Token Refresh Failing

### ISSUE THREAD

**Issue by doctorwheauxdat** [kuzmoyev/google-calendar-simple-api#29]
I do not know if this is something I am doing wrong, but after I authorize a flow and the token.pickle is created in my credentials the token fails to refresh. If I delete the token and run my script I have to authorize the flow again from a web browser, then I can use that token for a few minutes. Afterwards I have to delete it and authorize the flow again.

**Comment by kuzmoyev** [comment]
Now you can upgrade to `gcsa=0.3.1` with the fix.
