### ISSUE TITLE
Typo in interval handling

### ISSUE THREAD

**Issue by DirkReiners** [kuzmoyev/Google-Calendar-Simple-API#3]
I'm getting exception when trying to set an interval in the Recurrence. I think the problem is line 447 in recurrence.py should be 

`if interval and (not isinstance(interval, int) or interval < 1):`

instead of 

`if interval and (isinstance(interval, int) or interval < 1):`

That seems to fix it for me, at least. ;)

**Comment by kuzmoyev** [comment]
@DirkReiners Thank you for the issue submission. It is a typo. Fixed in dev.
