### ISSUE TITLE
Support multiple google accounts

### ISSUE THREAD

**Issue by seanbreckenridge** [kuzmoyev/google-calendar-simple-api#35]
Hi, thanks for maintaining this; having dealt with google sheets directly in the past this is a much nicer interface.

I have multiple accounts that I want to periodically back up, so I have multiple `credential.json` files, one which has API access to each google account.

Currently, this writes to the same static [`token.pickle`](https://github.com/kuzmoyev/google-calendar-simple-api/blob/c5a542d9e1ed5bba786b9c2f3eec236c4fd07df3/gcsa/google_calendar.py#L56) file to save credentials, so I can't use multiple files.

It fails with an error like:

```
    events = self.service.events().list(calendarId=self.calendar,
  File "/home/sean/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/sean/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/email-here/events?timeMin=1900-01-01T00%3A00%3A00-07%3A53&timeMax=2100-01-01T23%3A59%3A59.999999-08%3A00&orderBy=startTime&singleEvents=true&alt=json returned "Not Found">
```

... presumably because the email I'm requesting doesn't match the old credentials.

I think this could be pretty easily fixed by adding another kwarg to the GoogleCalendar constructor to specify a different `pickle` filepath.

I can create a PR if you're willing to merge that in. I haven't worked with `readthedocs` before, but I would think I just [add the parameter here?](https://github.com/kuzmoyev/google-calendar-simple-api/blob/c5a542d9e1ed5bba786b9c2f3eec236c4fd07df3/gcsa/google_calendar.py#L41-L42)

Perhaps the default could be `token.pickle`  (which gets combined into `os.path.join(self._credential_dir, 'token.pickle')?`; if a kwarg is provided it overwrites that filepath. Save that as `self._token_path` in `__init__` and then access that in `get_credentials`? Not too sure on how that should handle a filename like `other_token.pickle` vs a full path provided by the user/how that'd be documented in readthedocs.

Edit: realized its possible to do this if I put my credentials in different directories, but that seems like a bit of a hack.

**Comment by kuzmoyev** [comment]
Hi, thank you for the issue submission!

You are right, that needs to be resolved. Though I would prefer the ability to avoid specifying the name of the token file. So my initial idea (without much research) is to name it something like `<email>_token.pickle` if the email is available from the token or credentials (that should be unique). That could be discussed, not sure how to do it better yet.

If you have time to try it, I will appreciate a PR very much! Please do it towards the `dev` branch. I think it might lead to a new major version (1.0.0 is coming).

As for the docs, I'll need to add it to the [note](https://google-calendar-simple-api.readthedocs.io/en/latest/getting_started.html#credentials) ([here in code](https://github.com/kuzmoyev/google-calendar-simple-api/blob/master/docs/source/getting_started.rst#credentials)) about adding it to .gitignore.

I'll come back to it ASAP.

**Comment by seanbreckenridge** [comment]
`<email>_token.pickle` seems like it could work. Though if not provided that'd just be [`primary`](https://github.com/kuzmoyev/google-calendar-simple-api/blob/c5a542d9e1ed5bba786b9c2f3eec236c4fd07df3/gcsa/google_calendar.py#L29), which could cause some name conflicts. That could also lead to some non-determinism, if you're using multiple accounts. First account might get `primary_token.pickle` and then the other would have to default to some other filename, but if it was the other way, that would be confusing.

Another option could be the `project_id`, since from what I can see, [that cant be changed, and is what google uses](https://support.google.com/googleapi/answer/7014113?hl=en) to uniquely identify API keys. May be a bit dangerous to parse the JSON since not sure if google could change the standard. I'll experiment with the internals of the `credentials`/`service` object to see if thats exposed somewhere.

**Comment by seanbreckenridge** [comment]
Actually, since it [tries to read the pickle file before json](https://github.com/kuzmoyev/google-calendar-simple-api/blob/9c6c9087128d235b8adb99c6f7b63858f1639e00/gcsa/google_calendar.py#L58-L72) to use `flow.run_local_server`, isn't an obvious way to do this.

Looking at some of my older google API credentials it doesn't have the same structure so I don't think its wise to depend on the json structure in the `credentials.json` file.

If I'm mistaken about `<email>_token.pickle` let me know, else I'll continue to think if there's some other way to do this without passing a `kwarg` to explicitly change the file location.

**Comment by kuzmoyev** [comment]
Yep. You are right. The email isn't retrievable from credentials. So the only logical solution I see right now is to have an argument `token_path` that defaults to the same directory as `credentials.json` and `token.pickle` filename. So if `token_path` is `None` it'll get its path from the `credentials_path`. Which will be backward-compatible.

**Comment by seanbreckenridge** [comment]
Alright, I can take a shot at submitting a PR.

**Comment by seanbreckenridge** [comment]
Merged PR; closing
