### ISSUE TITLE
Add support for conference data

### ISSUE THREAD

**Issue by raju249** [kuzmoyev/google-calendar-simple-api#42]
Would be really helpful if someone can provide an example that helps adding the Google Meet link in the Calendar Event.

I am searching for this myself, if I get it first, I will post the solution here.

Thanks 🙏

**Comment by kuzmoyev** [comment]
Hello @raju249.

Unfortunately, gcsa does not support adding conference data natively. Thank you for the issue submission. I will add it to the library ASAP.

For now, you can use the following workaround:

```python
from datetime import date
from uuid import uuid4

from gcsa.event import Event
from gcsa.google_calendar import GoogleCalendar
from gcsa.serializers.event_serializer import EventSerializer

calendar = GoogleCalendar()

event = Event(
    'Event with meet data',
    start=date(2020, 9, 20),
    **{
        "conferenceData": {
            "createRequest": {
                "conferenceSolutionKey": {
                    "type": "hangoutsMeet"
                },
                "requestId": f"{uuid4().hex}"  # or you can use whatever id you'd like (has to be unique)
            }
        }
    }
)

body = EventSerializer(event).get_json()
event_json = calendar.service.events().insert(
    calendarId=calendar.calendar,
    body=body,
    conferenceDataVersion=1  # this parameter is what's missing in the gcsa implementation
).execute()


```


For more options  on `conferenceData` check out [official docs](https://developers.google.com/calendar/v3/reference/events)

**Comment by raju249** [comment]
Thanks for the quick prompt @kuzmoyev 

Really appreciate it. Thanks so much for the example. If I get some free time, I will raise a PR for this feature. But it will be awesome if you add it to.

Thanks again! Your library has made its way to my project dependencies.

Cheers! 🍺

**Comment by raju249** [comment]
Oh @kuzmoyev I was just checking the code. Would it be possible for me to pass access_token and refresh_token for using the user's Google Calendar ?

My workflow is as follows:
1. A user signs up using his google account and I get the offline access to his calendar.
2. I use this auth tokens for performing some action on user's calendar.

Right now, I think `gcsa` only accepts credentials file path for access.

Is there a workaround with this? 🤔

**Comment by kuzmoyev** [comment]
Ah. That's a thought I had when I just started the library a couple of years ago. Was waiting for the person that would actually need to pass the token manually, not from a file.

I guess a workaround could be to have a class that inherits the `GoogleCalendar` and override `_get_credentials` method:

```python

class GoogleCalendarWithToken(GoogleCalendar):
    @override
    def _get_credentials(self):
        # get token the way you'd like
```

But this deserves a separate issue.

**Comment by raju249** [comment]
Thanks @kuzmoyev 

I will use the workaround for now, and will monitor this issue to update the library when the fix is deployed.

Cheers 🍻

**Comment by raju249** [comment]
Thanks @kuzmoyev the overridden method works like charm. For others who stumble here for help, here is the code I wrote

```
from oauth2client.client import OAuth2Credentials

def _get_credentials(self):
    credentials = OAuth2Credentials(access_token=<access_token>,
                                    client_id=<google_client_id>,
                                    client_secret=<google_client_secret>,
                                    refresh_token=<refresh_token>,
                                    token_expiry=<token_expiry>,
                                    token_uri='https://oauth2.googleapis.com/token',
                                    user_agent='Python 3.6')
```

**Comment by Teraskull** [comment]
Yes, I also have this issue, as I need to use credentials on a flask server without pickling. Would be nice to have this option without the overriding workaround.
