### ISSUE TITLE
Deleting Events

### ISSUE THREAD

**Issue by DirkReiners** [kuzmoyev/Google-Calendar-Simple-API#5]
I am running into a 'str is not callable error' when trying to delete events. The problem seems to be in google_calendar.py:110 (GoogleCalendar::delete_event()). It should be

`if event.event_id is None:`

instead of 

`if event.event_id() is None:`

Making that change seems to fix it for me.

Thanks!

**Comment by kuzmoyev** [comment]
Thanks for the submission. Fixed in dev
