### ISSUE TITLE
Enable sending of invitations

### ISSUE THREAD

**Issue by kenomaerz** [kuzmoyev/google-calendar-simple-api#50]
It would be a relevant use case for me to send invitations to attendees. As far as I understand, this is not currently possible with gcsa. Are there any plans to support this? Would you be willing to accept a pull request? (no promises yet on delivery)

**Comment by kuzmoyev** [comment]
Good point. Thank you for the issue submission.

I'll add it in the next version. But PRs are very appreciated. If you create PR, please do so towards the `dev` branch.
For reference: this is a [documentation](https://developers.google.com/calendar/v3/reference/events/insert#sendUpdates) on how you send invitations.

And for now, you can just use `sendUpdates`(`**other`) parameter in `Event`:

```python

Event('event', attendees=['friend@gmail.com'], sendUpdates=True)
```
That should work, haven't tested it yet.

**Comment by kenomaerz** [comment]
Super neat of you to reply so quickly, much appreciated! I'll fiddle around a bit and let you know if I have something.

**Comment by kenomaerz** [comment]
So first of all, kudos to your remarkably clean code. I actually was able to this quickly in between dinner and getting the kid to go to sleep. All consideration in the PR. Thank you for building this!
