### ISSUE TITLE
404 Error when updating recurring events

### ISSUE THREAD

**Issue by kenomaerz** [kuzmoyev/google-calendar-simple-api#52]
The google API throws a 404 when trying to update instances of recurring events. Tested on the newest dev, was present on 0.4 as well. The parameters sent by gcsa seem to be correct to me, google must expect some special treatment of series when updating that I do not understand yet.

**Comment by kenomaerz** [comment]
https://developers.google.com/calendar/recurringevents

My understanding is that for updating the series, one would need to supply the RecurringEventId not, the eventid. gsca seems to supply the eventid, so from my point of view all should be fine.

**Comment by kenomaerz** [comment]
Sorry for doing turns here. Apparently, the problem only happens with recurring events that are not whole-day events.

**Comment by kuzmoyev** [comment]
Hmm. Ok. When an instance of a recurring event from `.list()`, I have this id:

```
74sm...6c_20201107t070000z
```

but, when I get an instance with `.instances`, I have this id:

```
74sm...6c_20201107T070000Z
```

If you can spot the difference, you'd be weirded out as I am and will understand the issue (I think). Will check if the second id works for update

**Comment by kuzmoyev** [comment]
Yes, the second id does work with update. So that's the issue. Will need to think about how to work with such events in the library

**Comment by kuzmoyev** [comment]
This is also the reason why whole-day events work as they don't have time part with mixed cases for t/T and z/Z

**Comment by kenomaerz** [comment]
Yes, I can confirm that this fixes my problems. No good idea how to handle it, unfortunately. Seem like an oversight on google's side.

**Comment by kenomaerz** [comment]
The standard defines T and Z to be uppercase:
https://en.wikipedia.org/wiki/ISO_8601
Given the fact that the API seems to expect that as well from passed ISs, I would tend to fix the IDs in the EventSerializer class, so correct IDs are used globally within the project. Code snippet I used in a hack from my local copy:
`tokens = event_id.split("_")
        if len(tokens) > 1:
            event_id = tokens[0] + "_" + tokens[1].upper()`

**Comment by kuzmoyev** [comment]
OMG 🤦‍♂️ . This is not a googles oversight. It is mine. I do the lowercasing in the `Event`s constructor. I've written it 2 years ago and now I'm not sure why.

And thanks to my love for unit-tests I could find that fixing it in the serializer doesn't work. So am fixing the real reason.

Again, thank you for finding this!

**Comment by kenomaerz** [comment]
Oh well. Happens to the best of us ;) Thanks for building this, will depend on it in future projects!
