### ISSUE TITLE
Is there a way to add timeout, when Google browser popup is closed?

### ISSUE THREAD

**Issue by Teraskull** [kuzmoyev/google-calendar-simple-api#54]
Right now, if you close the browser window, the script will hang, waiting for user permission.

Is there a way to add a timeout?

For example, the local server:

```python
credentials = flow.run_local_server()
```

If there are no credentials returned for 1 minute, close local server, and return error.

**Comment by kuzmoyev** [comment]
Hmm. It is not natively supported in gcsa. Couldn't find this possibility with `flow.run_local_server()`.

You can do it with 

```python
import signal

def signal_handler(signum, frame):
    raise Exception("Timed out!")

signal.signal(signal.SIGALRM, signal_handler)
signal.alarm(10)   # Ten seconds
try:
    gc = GoogleCalendar(...)
except Exception, msg:
    print "Timed out!"
```

I will think if I want to add it natively to the library

**Comment by Teraskull** [comment]
Thank you! Will try this solution. Closed for now.

**Comment by kuzmoyev** [comment]
I'll leave it open for now. It is a good feature to think about. And probably a common usecase.

**Comment by Teraskull** [comment]
Oh, once you opened the issue, I tried your solution, but there is no `signal.SIGALRM` on Winsows, so it does not work.

**Comment by Teraskull** [comment]
Ok, so I found an option that works on Windows.

Create a `timeout.py` file, and add this:

```python
import threading


class TimeoutError(Exception):
    pass


class InterruptableThread(threading.Thread):
    def __init__(self, func, *args, **kwargs):
        threading.Thread.__init__(self)
        self._func = func
        self._args = args
        self._kwargs = kwargs
        self._result = None

    def run(self):
        self._result = self._func(*self._args, **self._kwargs)

    @property
    def result(self):
        return self._result


class timeout(object):
    def __init__(self, sec):
        self._sec = sec

    def __call__(self, f):
        def wrapped_f(*args, **kwargs):
            it = InterruptableThread(f, *args, **kwargs)
            it.start()
            it.join(self._sec)
            if not it.is_alive():
                return it.result
            raise TimeoutError('execution expired')
        return wrapped_f

```

In `google_calendar.py` import `timeout` and add a decorator for `_get_credentials`, like this:

```python
from timeout import timeout

...

@timeout(60)  # 60 seconds, but we can also pass a custom int via the GoogleCalendar class.
def _get_credentials(self):
	...
```

And when creating a calendar, wrap it in a try/except:

```python
try:
	calendar = GoogleCalendar('primary', ...)
except TimeoutError:
	pass
```


Hope this helps, when implementing this feature!

**Comment by Teraskull** [comment]
Or, even a better option. The previous one has issues with catching other exceptions, and the timeout thread is not closed when finished, leading to future errors.

This code is the only one that worked for me on Windows, without any hidden bugs with closing threads.

```
$ pip install pebble
```

```python
from oauthlib.oauth2.rfc6749.errors import AccessDeniedError, MismatchingStateError
from gcsa.google_calendar import GoogleCalendar
from concurrent.futures import TimeoutError
from pebble import concurrent


@concurrent.process(timeout=60)  # Raise TimeoutError, if the function exceeds the given deadline (in seconds).
def create_calendar():
    calendar = GoogleCalendar('primary', credentials_path='credentials.json')
    return calendar


def do_something():
    try:

        calendar = create_calendar()  # Return calendar instance.
        calendar.result()  # Wait for process result, and receive exceptions, if any were raised.

    # Catch exceptions, received from process result.
    except TimeoutError:  # If user did not log into Google Calendar on time.
        pass

    except AccessDeniedError:  # If user denied access to Google Calendar.
        pass

    except MismatchingStateError:  # If user attempted to login using an outdated browser window.
        pass
```

**Comment by kuzmoyev** [comment]
That looks perfect. Thank you! I'll try to incorporate it into the library

**Comment by kuzmoyev** [comment]
Decided to not implement it into the library. Instead provided an example in the documentation if anybody needs this. Thank you @Teraskull for your suggestion!

**Comment by Teraskull** [comment]
Yes, this is a good idea. This feature is to vague to be useful for everyone. Thanks!

**Comment by Teraskull** [comment]
You have some typos in the docs, you can see them here: https://github.com/Teraskull/google-calendar-simple-api/commit/8ab725826c0eaab2b8352ea9baebdfd3d4507569

I don't want to open a whole PR for a few fixes. Just edit them yourself. Thanks.

**Comment by kuzmoyev** [comment]
Thanks, updated
