### ISSUE TITLE
How to move to other calendar

### ISSUE THREAD

**Issue by kenomaerz** [kuzmoyev/google-calendar-simple-api#56]
I fully expect this to be silly user error, but I'm stumped and would appreciate input:
After the initial Google Calendar API registration, everything worked fine. I now want to move to another calendar. What I did:

1. Activate the new calendar's api using https://developers.google.com/calendar/quickstart/python#step_1_turn_on_the (Selected "Dektop", AFAIK that is what gcsa requires?)
2. Replace the client_secret.json

After restarting the app, I can still only access the calendar from my original account, not the new one. No authorization window is popping up. What am I missing?

**Comment by kenomaerz** [comment]
Solved it - there is a token.pickle generated that went right past me. If that is present, apparently the credentials are left alone.

**Comment by kuzmoyev** [comment]
Yes, that's right.

You can also specify different `token_path` in `GoogleCalendar` to work with several accounts without a need to remove/regenerate tokens.

Will close the issue. If you think it needs some more attention LMK here.
