### ISSUE TITLE
Add calendars methods

### ISSUE THREAD

**Issue by kuzmoyev** [kuzmoyev/google-calendar-simple-api#62]
https://developers.google.com/calendar/v3/reference/calendarList
https://developers.google.com/calendar/v3/reference/calendars

**Comment by joshsny** [comment]
Let me know if I can help implementing this. Would be really helpful to have these in gcsa.

Also, I am confused at how I can access different calendars for the same person using gcsa?

**Comment by kuzmoyev** [comment]
For different user calendars, you can specify `GoogleCalendar(calendar=<calendar_id>)` parameter. See more in #7 (I really need to update the docs to make it more clear).

As for the calendar methods, I'd be very grateful for a PR, but it is a quite complicated piece of work and I'm not sure how to integrate it yet.

If you'd like to work on it, it would be better to decide on it here before the implementation. For instance, what object will be responsible for these methods (`GoogleCalendar` itself or other, something like `GoogleCalendarServise`. I'm thinking the latter)?

**Comment by kuzmoyev** [comment]
Also, as a workaround, you can use the `gc.service` to perform all the calendar/calendarList methods.

**Comment by joshsny** [comment]
Ah I must have not read the docs correctly, didn't see that I can use `gc.service` , that's very useful.

I worked on something similar and chose a different object like you suggest, then used `GoogleCalendarService` to return a list of `GoogleCalendar` objects. I'd contribute it here but the code is a complete mess.

Thanks for all the work you've put into this, it's been very useful!

**Comment by kuzmoyev** [comment]
I guess you're not supposed to use `gc.service` - that's the whole point of the library :) It's just a workaround, so it's not documented
