### ISSUE TITLE
Event serializer error for events with no summary

### ISSUE THREAD

**Issue by joshsny** [kuzmoyev/google-calendar-simple-api#67]
Though not marked as an optional field [here](https://developers.google.com/calendar/v3/reference/events), events returned from the calendar do not always contain a summary.

This causes the event serializer from gcsa to throw a key error.

To reproduce this error:

1) Create an event with no summary in your calendar.

2) Run something like this:

```python
for event in calendar:
  pass
```

**Comment by joshsny** [comment]
This can be fixed by switching out `json_event.pop('summary')` for `json_event.pop('summary', None)` in the event serializer.

**Comment by kuzmoyev** [comment]
@joshsny Thanks for finding this! Google's documentation isn't deterministic really :). Will fix that. Or will be very thankful if you could submit the PR for this small fix.

**Comment by joshsny** [comment]
I've submitted a PR (my first one!). Let me know if there are any problems.
