### ISSUE TITLE
problems specifying a calendar from my google account

### ISSUE THREAD

**Issue by g-velarde** [kuzmoyev/Google-Calendar-Simple-API#7]
I don't know how to specify a calendar named 'FJD' in order to create a new event. 

It only creates one in my primary calendar.

this my code

    from gcsa.event import Event
    from gcsa.google_calendar import GoogleCalendar

    from beautiful_date import Feb

    calendar = GoogleCalendar('mygoogleaccount@gmail.com')
    event = Event(
        'Python test',
        start=(25 / Feb / 2020)[20:00],
        minutes_before_email_reminder=50
    )

    calendar.add_event(event)

Thank you in advance

**Comment by kuzmoyev** [comment]
@g-velarde The first argument of `GoogleCalendar` is `calendar` which is equivalent to `calendarId` in official API. If you specify your email as `calendar`, your primary calendar is used. If you want another calendar, you need to specify its id. To find it, you can go to your [calendars](https://calendar.google.com/calendar/r), go to the settings of the needed calendar:
<img src="https://user-images.githubusercontent.com/15250762/75337040-864bc600-588c-11ea-847e-0e677b48a11c.png" width="400">

find its id:

![image](https://user-images.githubusercontent.com/15250762/75337491-62d54b00-588d-11ea-8952-614e0b208cbb.png)

and use it as a `calendar` argument in `GoogleCalendar`.

Please, let me know if it works. And thank you for the submission of the issue. I will update the documentation to make it more clear.

**Comment by g-velarde** [comment]
It works! 
Thanks
