### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

### ISSUE THREAD

**Issue by TheXer** [kuzmoyev/google-calendar-simple-api#70]
Hello,
I want to use your module for my discord bot. I have an issue with credentials as I writed in title. I put it in correct directory as you write in your documentary (~/.credentials/), but it doesn't work too. Did I downloaded the wrong file with credentials in it? I downloaded from official google documentary using your method in documentary, clicked on application and saved it in .credentials. 

Still doesn't work, maybe it is just me? 
Thanks for help if any.

**Comment by kuzmoyev** [comment]
You can try specifying a full path manually: `GoogleCalendar(credentials_path='<path>')`.

Also, what OS are you on? Windows/Linux/Mac?

**Comment by TheXer** [comment]
MacOS Big Sur, Python 3.8.2

**Comment by kuzmoyev** [comment]
Could you please provide a line where you create a `GoogleCalendar`?

**Comment by TheXer** [comment]
Interesting, I tried to put the code in different folder, now it shows this: 
`ImportError: No module named google.oauth2.credentials`

I have all the modules required installed and upgraded. The code is below - i tried to just test execute it for testing purposes so I can work with it more. 

`from google.oauth2.credentials import Credentials
from gcsa.event import Event
from gcsa.google_calendar import GoogleCalendar
from beautiful_date import Apr, hours


gc = GoogleCalendar(credentials_path='credentials.json')
calendar = GoogleCalendar('Xerousek@gmail.com')

start = (1/Apr/2020)[12:00]
end = start + 2 * hours
event = Event('Test vole',
              start=start,
              end=end)

calendar.add_event(event)`

**Comment by kuzmoyev** [comment]
`credentials_path` parameter overrides the default `~/.credentials/credentials.json` path. So it looks for the file in the directory you execute the script from. Remove `gc = GoogleCalendar(credentials_path='credentials.json')` line as it fails (and doesn't really do anything). The `calendar = GoogleCalendar('Xerousek@gmail.com')` should work.

**Comment by TheXer** [comment]
Perfect, that resolved my issue, thanks a lot! You could write that in documentary if possible.

**Comment by kuzmoyev** [comment]
Great! Glad that it worked.
