### ISSUE TITLE
Event has attribute color_id instead of color

### ISSUE THREAD

**Issue by joshsny** [kuzmoyev/google-calendar-simple-api#79]
The docs reference that the Event class has attribute color, but on reading the code the attribute is color_id.

**Comment by joshsny** [comment]
Also, generally there is a frustrating issue (with Google Calendar API) that events are not given a color if they take the default color of their calendar.

This means that given an event of default color, there is no way to access the event's color, since we don't have access to the calendar that it belongs to.

When I built something similar, I gave each event a property of the calendar that it belongs to to remedy this. Any thoughts on how best to solve this?

**Comment by kuzmoyev** [comment]
Good point about `color_id`. Even though `color_id` isn't documented as a field of the `Event` but as a constructor parameter, I think I'll rename the parameter to be consistent with the field to avoid any confusion. It is not a backward-compatible change, so it might be in a later update, not sure yet.

As for the `None` values for a default color, not sure how to address it and if it needs to be addressed. I understand that given the event, you can't get its color without the calendar. But is it an actual/common use case to have an event without having a `GoogleCalendar` object alongside? Genuinely curious about the use case as I can't really come up with one. Even with the given  color_id, you'd need a `GoogleCalendar` to translate it to something meaningful (from id to hex of a color)

**Comment by joshsny** [comment]
I'll explain in more detail my use case. I am analysing a users calendar data and categorising their events by color.

I don't care which calendar the events came from, just what color they are. For a user, if the event is a default calendar color or actual event color makes no difference. So for my use case, whether the event has no explicit color but belongs to a calendar with default color Peacock is the same as if it was explicitly colored peacock.

Therefore I'd really like to pull in all of the events in a users calendar once and forget about which calendars they came from, then pass events around to various functions. As it is now, I'd have to pass events together with their calendar/default calendar color.

I don't think I'd need a `GoogleCalendar` to translate the color_id to something meaningful, my impression is that `https://developers.google.com/calendar/v3/reference/colors/get` returns the same result regardless of the user.

**Comment by kuzmoyev** [comment]
Got you.

You are right that `/colors/get` is the same for any user. The default calendar color is received from [CalendarList](https://developers.google.com/calendar/v3/reference/calendarList) endpoint(s).

I think that the automatic population of the `Event`s `color` field in case of the default color is redundant (or might be even harmful as it loses the fact that it's the default), so it should be done by a developer in case it is needed (as in your case). The problem of `gcsa` though is that it does not implement `CalendarList` endpoint functionality. So it is in a pipeline to be implemented. 

So as you can use a `service` field from `GoogleCalendar` you could get it yourself:


```python
...

default_color_id = gc.service.calendarList().get(calendarId=gc.calendar).execute()['colorId']
...

events = []
for e in gc:
    e.color_id = default_color_id if e.color_id is None else e.color_id
    events.append(e)
```
