### ISSUE TITLE
Unsupported MIME Types for Google Doc Attachments

### ISSUE THREAD

**Issue by andrewcrumrine** [kuzmoyev/google-calendar-simple-api#83]
I'm receiving this error when getting events with a Google Doc attachment.

``` 
 ValueError: Mime type application/vnd.google-apps.kix is not supported.
```

I found [this post](https://gist.github.com/javan/7343255) that recommends using undocumented MIME types for Google doc attachments in addition to the documented MIME types.

**Comment by kuzmoyev** [comment]
Hello. Yes, it is an issue that is fixed in #69 (Dev).

As a workaround, you can set `mime_type` manually to avoid tihs check:

```
a = Attachment(file_url='<your URL')
a. mime_type = 'application/vnd.google-apps.kix'
```

**Comment by andrewcrumrine** [comment]
Actually I'm trying to retrieve a list events that already contain unsupported attachments using the `get_events` method.

**Comment by kuzmoyev** [comment]
Got you.

It will be fixed in the next version. Unfortunately, Google's docs are not very explicit about it, so still tweaking the gcsa to work correctly with the help of developers like yourself.

Thank you for the issue submission.
