### ISSUE TITLE
Cannot add 5th reminder

### ISSUE THREAD

**Issue by gaborantal** [kuzmoyev/google-calendar-simple-api#86]
In event.py, an if condition is badly set to ">4", however it should be set to ">5".

**Comment by kuzmoyev** [comment]
You can add a reminder if there are 4 or fewer reminders. So the 5th reminder would be added without raising an exception. So `>4` will be triggered only if you already have 5 (or more for some reason) reminders.

**Comment by kuzmoyev** [comment]
I've tried it. Works fine for me. You shouldn't have issues adding 5 reminders.

**Comment by kuzmoyev** [comment]
Closing an issue for now. I believe this part works correctly.

If you think this needs more attention, please let me know here.

**Comment by gaborantal** [comment]
Thanks for your comments! I think I got the error any ways, however it may be caused by my own modifications in the source code. I'll review my work and contact you if I have anything.
