### ISSUE TITLE
Issue: Has Something Changed In Google's Python Quickstart?

### ISSUE THREAD

**Issue by jeffehobbs** [kuzmoyev/google-calendar-simple-api#88]
From this page:

https://google-calendar-simple-api.readthedocs.io/en/latest/getting_started.html

Following these instructions:

1. Go to Calendar API Quickstart
2. Click ENABLE THE GOOGLE CALENDAR API
3. Click DOWNLOAD CLIENT CONFIGURATION

After step 2, I get the resultant dialog with no option to "download the client configuration":

<img width="620" alt="google_dialog" src="https://user-images.githubusercontent.com/466625/109418581-299b5380-7997-11eb-80b1-479c17a1cda2.png">

Has this authentication flow changed or am I missing something?

**Comment by kuzmoyev** [comment]
I guess it did change. Thank you for noting that. I will add this to the docs. But if you hit `create` you'll be able to download the credentials.
