### ISSUE TITLE
Possible UX optimisations

### ISSUE THREAD

**Issue by kuzmoyev** [kuzmoyev/google-calendar-simple-api#96]
Consider me a beginner but you are right, thanks ! I found gcsa incredibly easy to use, it is well documented and the example you gave is very helpful. These are the obstacles I faced:

- I had to work my way around authenticating multiple Google Calendars, it turns out that a tab opens in the browser if you create a new token, so maybe an example that shows authentication of multiple Google Calendars would be helpful
- ~~I had to use `dir` to figure out the methods and attributes of the Event object, I found them later on "Read the docs"~~
- ~~I had to calculate "Duration", having a duration attribute could be helpful~~

I hope this helps, great job on gcsa !

_Originally posted by @msulaim in https://github.com/msulaim/API-and-REST/issues/3#issuecomment-806330467_

**Comment by joshsny** [comment]
I'm not sure having a duration attribute on the event would make sense, it would allow one to modify the duration without modifying the start and end attributes of an event.

**Comment by kuzmoyev** [comment]
@joshsny Not sure if I want to have it yet. But it could be that you need to specify any two (and only two) of `start`, `end`, and `duration` from which you can calculate the `start` and `end`.
