### ISSUE TITLE
Can this be extended for multi-user? (i.e. controlling calendar on behalf of other users)

### ISSUE THREAD

**Issue by taewookim** [kuzmoyev/google-calendar-simple-api#98]
I'm trying to create /read events for other users, not mine, via oauth
Is it possible to extend this library to do that?

**Comment by kuzmoyev** [comment]
Hello, thank you for the issue submission. 

What do you mean by "other users"? To use `gcsa` with multiple users you need to specify `credentials_path` and `token_path` for each user (see more [here](https://google-calendar-simple-api.readthedocs.io/en/latest/authentication.html#credentials-file)).

```
gc = GoogleCalendar(credentials_path='path/to/credentials.json',
                    token_path='another/path/user1_token.pickle')
```

Or just pass different [toke objects](https://google-calendar-simple-api.readthedocs.io/en/latest/authentication.html#token-object).

In the future, if you have a question, not an issue, try posting it in [GH discussions](https://github.com/kuzmoyev/google-calendar-simple-api/discussions) first.

Please, let me know if that answers your question and if I can close the issue.

**Comment by kuzmoyev** [comment]
I will close the issue for now. If you have any questions, please, open a new discussion.
